---
- name: Get apps to install
  set_fact:
    apps_list: "{{ apps[plan] if plan is defined else apps_to_install.split(',') }}"

- name: Install apps
  block:
    - name: Install each app
      command:
        chdir: "{{ bench_path }}"
        cmd: "bench --site {{ site_name }} install-app {{ item }}"
      loop: "{{ apps_list }}"
      register: app_install

    - name: Run migrations
      command:
        chdir: "{{ bench_path }}"
        cmd: "bench --site {{ site_name }} migrate"
      when: app_install is success

    - name: Clear cache
      command:
        chdir: "{{ bench_path }}"
        cmd: "bench --site {{ site_name }} clear-cache"
      when: app_install is success
