# site_prov/site_prov/site_prov/ansible/roles/install_apps/tasks/main.yml
---
- name: Get apps to install
  set_fact:
    apps_list: "{{ apps[plan] }}"
  when: plan is defined

- name: Install apps
  block:
    - name: Show apps to install
      debug:
        msg: "Installing apps: {{ apps_list }}"

    - name: Install each app
      command:
        chdir: "{{ bench_path }}"
        cmd: "bench --site {{ site_name }} install-app {{ item }}"
      loop: "{{ apps_list }}"
      register: app_install

    - name: Run migrations after apps install
      command:
        chdir: "{{ bench_path }}"
        cmd: "bench --site {{ site_name }} migrate"
      when: app_install is success

    - name: Clear cache
      command:
        chdir: "{{ bench_path }}"
        cmd: "bench --site {{ site_name }} clear-cache"
      when: app_install is success

  rescue:
    - name: Log error
      debug:
        msg: "Failed to install apps: {{ app_install }}"
      failed_when: true