# site_prov/site_prov/site_prov/ansible/site_setup.yml
---
- name: Setup Frappe Site
  hosts: localhost
  connection: local  # Add this line
  become: no
  gather_facts: yes  # Change to yes for debugging

  vars:
    bench_path: "/home/frappe/frappe-bench"
    apps:
      Plan 1:
        - erpnext
      Plan 2:
        - erpnext
        - hrms
      Plan 3:
        - erpnext
        - hrms
        - helpdesk

  pre_tasks:
    - name: Debug Variables
      debug:
        msg:
          - "Site Name: {{ site_name }}"
          - "Plan: {{ plan }}"
          - "Bench Path: {{ bench_path }}"
          - "Working Directory: {{ lookup('env', 'PWD') }}"

    - name: Ensure bench path exists
      stat:
        path: "{{ bench_path }}"
      register: bench_dir
      
    - name: Fail if bench path doesn't exist
      fail:
        msg: "Bench directory not found at {{ bench_path }}"
      when: not bench_dir.stat.exists

  tasks:
    - name: Create new site
      include_role:
        name: create_site
        apply:
          tags: create_site
      when: site_name is defined and plan is defined
      tags: ['create_site']
